# Generated by Django 6.0 on 2026-01-02 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_codesubmission_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub')], default='github', max_length=20)),
                ('provider_account_id', models.CharField(help_text='GitHub account UID (from SocialAccount) that has access to this repo', max_length=255)),
                ('repo_id', models.CharField(help_text='GitHub repository ID (numeric)', max_length=255)),
                ('owner', models.CharField(help_text='Repository owner (username or organization)', max_length=255)),
                ('name', models.CharField(help_text='Repository name', max_length=255)),
                ('full_name', models.CharField(help_text='Full repository name (owner/repo)', max_length=500)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('private', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('html_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.CreateModel(
            name='RepoSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, help_text='Error message if sync failed')),
                ('files_count', models.IntegerField(default=0, help_text='Number of files in last sync')),
                ('branches_count', models.IntegerField(default=0, help_text='Number of branches tracked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_status', to='core.repository')),
            ],
            options={
                'verbose_name_plural': 'Repository Syncs',
            },
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['user', 'provider'], name='core_reposi_user_id_f6f855_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['provider_account_id'], name='core_reposi_provide_e181f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('user', 'provider', 'repo_id')},
        ),
    ]
